#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : swupd-probe
Version  : 2
Release  : 3
URL      : https://github.com/clearlinux/swupd-probe/archive/v2.tar.gz
Source0  : https://github.com/clearlinux/swupd-probe/archive/v2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: swupd-probe-bin
Requires: swupd-probe-config
Requires: swupd-probe-doc
BuildRequires : pkgconfig(systemd)

%description
## swupd-probe
This project creates an interface between swupd-client and
telemetrics-client. The goal of the project is to provide
highly reliable and safe telemetry of swupd-client events
to telemetrics-client.

%package bin
Summary: bin components for the swupd-probe package.
Group: Binaries
Requires: swupd-probe-config

%description bin
bin components for the swupd-probe package.


%package config
Summary: config components for the swupd-probe package.
Group: Default

%description config
config components for the swupd-probe package.


%package doc
Summary: doc components for the swupd-probe package.
Group: Documentation

%description doc
doc components for the swupd-probe package.


%prep
%setup -q -n swupd-probe-2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1486428075
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1486428075
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/swupd-probe

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/swupd-probe.path
/usr/lib/systemd/system/swupd-probe.service

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
